apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: backend
  name: backend
  namespace: proyecto

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: dottogc/python-flask-distroless
        name: python-webservice
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-srv
  namespace: proyecto
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend
  type: LoadBalancer
