apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: frontend
  name: frontend
  namespace: proyecto

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: dottogc/golang-webserver-distroless
        name: golang-webservice
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-srv
  namespace: proyecto
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
